server:
  port: 8095

spring:
  application:
    name: verify-topic-provider
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.3.200
    port: 5672

#自定义配置
mq:
  config:
    exchange: log.topic #设置交换器名

