server:
  port: 8096

spring:
  application:
    name: verify-fanout-consumer
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.3.200
    port: 5672

#自定义配置
mq:
  config:
    exchange: order.fanout #设置交换器名
    queue:
      sms:
        queue-name: order.sms #队列名称
      push:
        queue-name: order.push